### ISSUE TITLE
Wrong  check path when configuring grafana with individual dashboards

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#11]
In file main.yml from grafana role in [line]( https://github.com/HolgerHees/smartserver/blob/7ba8a7ecb2291953af17fd9f16e09b466630863e/roles/grafana/tasks/main.yml#L39) is checked for wrong dashboards folder. 

Should be similar with the path in [this](https://github.com/HolgerHees/smartserver/blob/7ba8a7ecb2291953af17fd9f16e09b466630863e/roles/grafana/tasks/main.yml#L47) line.

**Comment by HolgerHees** [comment]
thanks for finding. Was a leftover after some refactorings.
