### ISSUE TITLE
Edge case - image_proxy.php never ends

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#13]
Hello Holger,

I've tried to use your recent changes to gallery and I think I found a edge case that may lead to image_proxy.php to never ends.

In my environment (the cameras are not configured to accept Basic auth or the format returned is not recognized by Imagick) seems that  [curl_exec](https://github.com/HolgerHees/smartserver/blob/e0b2c612481b99d8432af7b3c5a52156af9e4071/roles/apache_gallery/templates/htdocs/gallery/image_proxy.php#L93) of the camera snapshot url may throw an exception, and then in subsequent calls the [apcu_delete( $url . ":fetch" );](https://github.com/HolgerHees/smartserver/blob/e0b2c612481b99d8432af7b3c5a52156af9e4071/roles/apache_gallery/templates/htdocs/gallery/image_proxy.php#L120) never called and the [loop](https://github.com/HolgerHees/smartserver/blob/e0b2c612481b99d8432af7b3c5a52156af9e4071/roles/apache_gallery/templates/htdocs/gallery/image_proxy.php#L52) never exit. The workaround is to restart the php container to clean the cache.

PHP logs looks like (with some of your debugging statements uncommented):
```
NOTICE: PHP message: fetch http://hostname/ipcamera/cam01/ipcamera.jpg
NOTICE: PHP message: 0.0033631324768066
NOTICE: PHP message: fetched size 282
NOTICE: PHP message: calculated size 282
NOTICE: PHP message: PHP Fatal error:  Uncaught ImagickException: no decode delegate for this image format `' @ error/blob.c/BlobToImage/363 in /dataDisk/htdocs/gallery/image_proxy.php:148
Stack trace:
#0 /dataDisk/htdocs/gallery/image_proxy.php(148): Imagick->readImageBlob()
#1 /dataDisk/htdocs/gallery/image_proxy.php(101): scaleImage()
#2 /dataDisk/htdocs/gallery/image_proxy.php(65): fetchUrl()
#3 /dataDisk/htdocs/gallery/image_proxy.php(14): getData()
#4 {main}
  thrown in /dataDisk/htdocs/gallery/image_proxy.php on line 148
``` 

Maybe you consider fixing this by handling such exception and cleanup the cache.

**Comment by toffee** [comment]
The ImagickException occurs 
```
NOTICE: PHP message: PHP Fatal error:  Uncaught ImagickException: Zero size image string passed in /dataDisk/htdocs/gallery/image_proxy.php:148
```
because the snapshot url is not generated correctly.

In my custom_camera.conf the snapshot url looks like:
`http\%3A//192.168.120.51/ISAPI/Streaming/channels/102/picture` (please notice **\\** after http).

If I manually correct the url but the camera does not support basic auth (support only digest) the exception is:
```
NOTICE: PHP message: PHP Fatal error:  Uncaught ImagickException: no decode delegate for this image format `' @ error/blob.c/BlobToImage/363 in /dataDisk/htdocs/gallery/image_proxy.php:148
```

**Comment by HolgerHees** [comment]
Hi,

thanks for finding. I was not expecting that you use / adapt it so fast in your setup :-)

it should be fixed in?

https://github.com/HolgerHees/smartserver/commit/a2a14639259be74f4f4135154bd1d32a595b081a

1. It should catch fatal exceptions to free up the apc lock
2. It should support any auth type supported by curl automatically

The idea, of the whole refactoring, is to simplify the setup and make it more reusable. Before it was based on a much more "complicated" custom apache config, which I had to duplicate in my setup and some setups of friends of me.

**Comment by toffee** [comment]
Hello and thank you!

I confirm that the issue is fixed. Also, now it's possible to authenticate to IP camera  with digest.
