### ISSUE TITLE
Smartd temperature is too high (HDD/SSD) not restrictive enough

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#15]
Prometheus has some internal [metrics](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PrometheusAlertStartTimeStuff) like ALERTS_FOR_STATE that contains the timestamp when an alert was triggered. This metric contains all alert labels and one additional 'alertname'. 

I think the [expression](https://github.com/HolgerHees/smartserver/blob/92e0f1272a454f729762594e8414c883a475341a/roles/hardware_smartd/templates/prometheus/rules.yml#L5) for this alert is not restrictive enough because after a alert is triggered it will not be removed any more (not even after the condition that triggered the alert is false).

I propose the expression to be changed to (exclude timeseries ALERTS_FOR_STATE - eg. the ones without label alertname):
```{alertname="",chart=~"smartd_log.*",family="temperature",job="netdata"} > 50```

I'm not sure if this should be applied to other alerts... 

The situation in my system after the alert is ended:
![image](https://github.com/HolgerHees/smartserver/assets/1410861/29d6fe49-bf27-4a5f-8306-aff7d6a0f78b)

**Comment by HolgerHees** [comment]
Hi, thanks for reporting. Can you check if it helps?

**Comment by toffee** [comment]
Hello. Thanks for fixing but I don't think this will work in my system. I have different metric name - contains "airflow" in the name.
See bellow the metrics starting with _netdata_smartd_log_:

![image](https://github.com/HolgerHees/smartserver/assets/1410861/af0aae8c-1963-49d7-aad2-6b23d7571bc4)

**Comment by HolgerHees** [comment]
can you please try again

**Comment by toffee** [comment]
The same, the chart label contains the "airflow" text in the name

I put below a picture with metrics returned in my systems for _family="temperature",job="netdata"_
![image](https://github.com/HolgerHees/smartserver/assets/1410861/7ce30981-7e30-4a04-8bd4-ded3fe27240e)

As you can see - the metric (netdata_smartd_log_**airflow**_temperature_celsius_celsius_average) and the chart (smartd_log.**airflow**_temperature_celsius) contains "airflow".

Also you can see the metric ALERTS_FOR_STATE when a alert is fired.

Why my initial proposal it's not ok (to exclude metrics that have the label "alertname")?

**Comment by HolgerHees** [comment]
I think, now I fully understand the problem

https://github.com/HolgerHees/smartserver/commit/055ca6471fbc31c246d89153b3c3b1f7d78023e2

**Comment by toffee** [comment]
Yes, I think ```__name__=~"netdata.*``` do the magic. Thank you!
