### ISSUE TITLE
No VLANs in my librenms

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#16]
I'm trying to solve the alerts that I have. With this issue I would like to let you now the special situation - maybe you consider and make the code more robust. 

The alert is _System service service state_ with prometheus expression ```system_service_state{job="system_service",hostname=""} == 0``` which gets triggered because in my systems librenms has no VLANs (Don't know if it's wrong configuration or my switch - TP-Link - does not provide those information via SNMP). 

The [call](https://github.com/HolgerHees/smartserver/blob/055ca6471fbc31c246d89153b3c3b1f7d78023e2/roles/system_service/templates/opt/system_service/lib/scanner/handler/librenms.py#L159) returns 404:
```
# curl -H 'X-Auth-Token: XXXXXX' http://librenms:8000/api/v0/resources/vlans
{
    "status": "error",
    "message": "VLANs do not exist"
}
```

If I modify the code to print the stacktrace I see: 
```
Traceback (most recent call last):
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 45, in _run
    self._processLibreNMS()
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 80, in _processLibreNMS
    self._processVLANs()
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 160, in _processVLANs
    _vlan_json = self._get("resources/vlans")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 319, in _get
    raise NetworkException("Got wrong response status code: {}".format(r.status_code), self.config.startup_error_timeout if not self._isInitialized() else self.config.remote_suspend_timeout)
lib.scanner.handler.librenms.NetworkException: Got wrong response status code: 404
```

For now I commented the call to [_processVLANs](https://github.com/HolgerHees/smartserver/blob/055ca6471fbc31c246d89153b3c3b1f7d78023e2/roles/system_service/templates/opt/system_service/lib/scanner/handler/librenms.py#L79) and [_processFDP](https://github.com/HolgerHees/smartserver/blob/055ca6471fbc31c246d89153b3c3b1f7d78023e2/roles/system_service/templates/opt/system_service/lib/scanner/handler/librenms.py#L85C18-L85C29) and the alert is gone. 

I don't know if this situation may appear to others (and code need to be changed to consider this) or I need to configure librenms /switch to report VLANs.

**Comment by HolgerHees** [comment]
Thanks again for reporting. Every found bug makes it more stable and useable :-)

can you please check 

https://github.com/HolgerHees/smartserver/commit/932fc75ef9a37ddf15b948f8023acd1a2ba3da61

I implemented a vlan fallback handling in case that vlans does not exists.

**Comment by toffee** [comment]
Thank you very much. I thing the fallback mechanism will work. Now I get an error (I guess the fix would be to assign to 404 error code an object not an array):

```
[ERROR] - [anner.handler.librenms:61] - LibreNMS got unexpected exception. Will suspend for 15.0 minute(s).
[ERROR] - [anner.handler.librenms:61] - Traceback (most recent call last):
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 49, in _run
    self._processLibreNMS()
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 83, in _processLibreNMS
    self._processVLANs()
  File "/opt/system_service/lib/scanner/handler/librenms.py", line 166, in _processVLANs
    _vlans = _vlan_json["vlans"]
             ~~~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by HolgerHees** [comment]
I guess, one array level too much.

https://github.com/HolgerHees/smartserver/commit/783783ba5cfbe5d11806c553e28ca760e71b9513

**Comment by toffee** [comment]
Everything fine now. Thank you!
