### ISSUE TITLE
Weather service - local mqtt mode, StationConsumer is needed?

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#17]
Next alarm in my systems - maybe discovered another issue!? 

In my system the alarm _Weather consumer (station)_ is triggered because nobody publish data into the mqtt topic _+/weather/**station**/#_ The openmeteo provider publish to  _+/weather/**provider**/_ so the [has_any_updates](https://github.com/HolgerHees/smartserver/blob/783783ba5cfbe5d11806c553e28ca760e71b9513/roles/weather_service/templates/opt/weather_service/lib/consumer/station.py#L90) is always False

I think the [StationConsumer](https://github.com/HolgerHees/smartserver/blob/783783ba5cfbe5d11806c553e28ca760e71b9513/roles/weather_service/templates/opt/weather_service/weather_service#L51) should be instantiated only for cloud_mosquitto - but maybe I misunderstood your [documentation](https://github.com/HolgerHees/smartserver/blob/783783ba5cfbe5d11806c553e28ca760e71b9513/config/default.yml#L528)

**Comment by HolgerHees** [comment]
The idea of the StationConsumer is to merge data with data from a real weather station. If there are no weather station, the data are coming from the weather provider (e.g. openmeteo)

ArduinoExample: https://github.com/HolgerHees/arduino_weatherstation/blob/master/arduino_weatherstation_mini.ino

The StationConsumer it is now configurable (https://github.com/HolgerHees/smartserver/commit/ea4fc898ee5660de2df2520ef4a93da50701f659) with the key "weather_mqtt_station_consumer_topic"), but optional/disabled by default

in Openhab (https://github.com/HolgerHees/openhab-config/blob/master/templates/things/mqtt.things), i receive values from my weatherstation (Topic: mysensors-pub.*, e.g. line 82) and forward some of them to the station_consumer_topic (Topic: hhees/weather/station/.*, e.g. line 23)

The forward itself is happend here https://github.com/HolgerHees/openhab-config/blob/master/conf/items/sensors.items (e.g. line 172)

**Comment by toffee** [comment]
Thank you very much for explanations and changes. 

I have an of-the-shelf weather station that in openHAB is using [this](https://www.openhab.org/addons/bindings/fineoffsetweatherstation/) binding.  I will try to forward the data from the weather station to a new created mqtt thing (to have my environment similar with your) - but that for another day.

This evening, the alarm disappeared with default weather_mqtt_station_consumer_topic, thanks to your modification.

**Comment by toffee** [comment]
Need more changes:

```
[INFO] - [lib.provider.provider:175] - <class 'AttributeError'>: module 'config.config' has no attribute 'publish_topic'
Traceback (most recent call last):
  File "/opt/weather_service/lib/provider/provider.py", line 135, in fetch
    fetcher.fetchForecast(self.mqtt)
  File "/opt/weather_service/lib/provider/openmeteo.py", line 190, in fetchForecast
    msg = "{}/weather/provider/forecast/{}/{}".format(self.config.publish_topic,field,date)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config.config' has no attribute 'publish_topic'
[INFO] - [lib.provider.provider:186] - Sleep 600 seconds
```

**Comment by HolgerHees** [comment]
https://github.com/HolgerHees/smartserver/commit/a82c65e955634c888ad9e08a83067d482b6d8c0a

**Comment by toffee** [comment]
The name of the [ansible variable](https://github.com/HolgerHees/smartserver/blob/6fb511e13561212e5a2228aae283c247216d51c4/config/default.yml#L541C5-L541C31) should contains "provider" too. Otherwise the [config.py variable](https://github.com/HolgerHees/smartserver/blob/6fb511e13561212e5a2228aae283c247216d51c4/roles/weather_service/templates/config.py#L8) is initialized with False

I found out that looking at mqtt topic name:
<img width="265" alt="image" src="https://github.com/HolgerHees/smartserver/assets/1410861/514da6f2-8ce5-43f2-a20b-aed68f5a2f0b">

**Comment by HolgerHees** [comment]
my fault. the related change was lost during a cleanup https://github.com/HolgerHees/smartserver/commit/de457862272deedffb76195ab1a0d351eee7b16a

it is fixed now https://github.com/HolgerHees/smartserver/commit/64ae4c6f25e6f9f07e982cff7e42a3ed637e7aaf

**Comment by HolgerHees** [comment]
additionally I validate configuration in weather_service too https://github.com/HolgerHees/smartserver/commit/8dac14f6d52e0405991fe18087771334ff41319d
