### ISSUE TITLE
Visualizer escape codes

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#19]
In my systems container visualizer display:

![image](https://github.com/user-attachments/assets/131feaee-e0ae-45be-8c18-f3ced51c2372)

If I change the escape code for [background](https://github.com/HolgerHees/smartserver/blob/7b7467b0e02b229bfb4446484b7e4d5d17abd185/roles/container/templates/opt/container/visualizer#L522) to ```;48;2;50;50;50``` it's displayed ok. I'm not sure it's a defect or something is wrong configured in my system.

I'm connected via SSH with PuTTY.

**Comment by HolgerHees** [comment]
works for me too, so it is fixed in

https://github.com/HolgerHees/smartserver/commit/9e281da1880973346bf768e1ad1c672077e7bb27
