### ISSUE TITLE
How about including Telegraf?

### ISSUE THREAD

**Issue by hooperbloob** [HolgerHees/smartserver#2]
Telegraf broadens the number of entry points for Influxdb and makes collecting metrics much easier.

**Comment by HolgerHees** [comment]
I added an prototype of a telegraf role.

https://github.com/HolgerHees/smartserver/tree/master/roles/telegraf

Feel free to enable it in your config and provide feedback. It is currently untested. Specially the fluentd part.

**Comment by HolgerHees** [comment]
is now available
