### ISSUE TITLE
Use pihole as reverse DNS

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#20]
Network structure functionality use intensively reverse DNS. I've enabled pihole as reverse DNS in dnsmasq - see [commit](https://github.com/toffee/smartserver/commit/8af5417f0d7c9c1c17be159d2c3d92a206158a3b) At that time worked without changes in firewall but now seems that nftables blocks connections from dnsmasq to pihole on posrt 53:

```
[Wed Sep 11 16:27:54 2024] DROP [INET FORWARD]: IN=podman1 OUT=mac0 MAC=ea:40:c2:43:ce:1f:5a:96:cb:e9:2b:17:08:00 SRC=172.16.0.100 DST=192.168.120.250 LEN=73 TOS=0x00 PREC=0x00 TTL=63 ID=32605 DF PROTO=UDP SPT=56045 DPT=53 LEN=53
[Wed Sep 11 16:27:56 2024] DROP [INET FORWARD]: IN=podman1 OUT=mac0 MAC=ea:40:c2:43:ce:1f:5a:96:cb:e9:2b:17:08:00 SRC=172.16.0.100 DST=192.168.120.250 LEN=73 TOS=0x00 PREC=0x00 TTL=63 ID=32860 DF PROTO=UDP SPT=52028 DPT=53 LEN=53
```

I've modified today the dnsmasq [main.yml](https://github.com/toffee/smartserver/commit/df62db57a52c9e7f13296777bcdce765296842f9) to permit (maybe this should be only when dhcp_type == 'pihole').

Maybe you want to include these changes in your code base.

**Comment by HolgerHees** [comment]
thanks for sharing...

I added both changes to my code base

https://github.com/HolgerHees/smartserver/commit/8e23f6a410aeb4c9112cf37bf117024bca7ff2ee
