### ISSUE TITLE
nextcloud email server configuration

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#24]
Starting to use nextcloud for calendar via WebDav. As it is now it's working for events without attendees. If you add an attendee (which may have any email address) it does not receive the invitation by email. Instead the email is received by email configured with {{root_email}} because that's the configuration of postfix in canonical_maps_recipient file.

My [simple solution](https://github.com/toffee/smartserver/commit/e0721bbfd65fbecb5bde8cd0a7a9d28c9fa14163) is to [configure nextcloud email](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html) with relay server used by postfix.

Don't know if you want all the emails to be routed via postfix or this solution is ok.

**Comment by HolgerHees** [comment]
like https://github.com/HolgerHees/smartserver/commit/775a481500ac1842f1a7063c7af2192317cf60e5

**Comment by HolgerHees** [comment]
one more fix https://github.com/HolgerHees/smartserver/commit/601300f6cddf44e49b850941cb03574ff5fd862c

**Comment by HolgerHees** [comment]
@toffee does this solution works for you?

**Comment by toffee** [comment]
Not tested yet, but I will do it now and confirm.

**Comment by toffee** [comment]
Yes, it's working. Thanks!
