### ISSUE TITLE
nextcloud admin user really needed?

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#25]
I see that you create a special admin user for nextcloud (additionally there is one for webui) for accessing the nextcloud web interface with admin rights. 

I'm wondering if it's not easy (and less to maintain) if you grant admin privileged to users from {{userdata}} in group admin?

I see it's possible to assign an user to a group using:

```
wwwrun@php:~$ /smartserver/htdocs/nextcloud/occ group:adduser admin <username>
```

That's the method I used to get access to nextcloud admin interface with my user (not using the admin - that now I consider useless, but maybe I don't see the full picture).

**Comment by HolgerHees** [comment]
makes sense to me.

https://github.com/HolgerHees/smartserver/commit/a69360da7033fbac4567cceedcfed997d7778c35
