### ISSUE TITLE
force pdman image deletion

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#26]
Running /opt/container/clean_images -q from deployment update gives me the error:

```
Start cmd 'deployment_update' - '/opt/container/clean_images -q'

Traceback (most recent call last):
00:23:34.933   File "/opt/container/clean_images", line 191, in 
00:23:34.934     command.exec(["podman", "image", "rm", "{}".format(image.id)])
00:23:34.934   File "/usr/lib/python3.6/site-packages/smartserver/command.py", line 78, in exec
00:23:34.934     raise Exception(result.stdout.decode("utf-8"))
00:23:34.935 Exception: Error: unable to delete image "b559f5a6c8aa68b673b22d960451cecaab09da11602574b2f718a04c2d721793" by ID with more than one tag ([mirror.gcr.io/dpage/pgadmin4:8.11.0 mirror.gcr.io/dpage/pgadmin4:8.11]): please force removal
00:23:34.935 

Error: unable to delete image "b559f5a6c8aa68b673b22d960451cecaab09da11602574b2f718a04c2d721793" by ID with more than one tag ([mirror.gcr.io/dpage/pgadmin4:8.11.0 mirror.gcr.io/dpage/pgadmin4:8.11]): please force removal
```

As mentioned in the error, I delete manually the image using force option like:
```
podman image rm --force b559f5a6c8aa
```

Probably make sense to put this switch in [your code](https://github.com/HolgerHees/smartserver/blob/878cf29955a24d96dd2505dd0e4c6baea9ce4d3c/roles/container/templates/opt/container/clean_images#L191) too

**Comment by HolgerHees** [comment]
that's strange. How does this happen?

I try to avoid the "--force" flag. Before I try to cleanup everything, so the "--force" flag should not be necessary. Was this image stilled used by another image or a container?

**Comment by toffee** [comment]
I have an application that needs postgres as database - and created roles for [postgres](https://github.com/toffee/smartserver/tree/jupiter/roles/postgres) and web administration [pgadmin](https://github.com/toffee/smartserver/tree/jupiter/roles/pgadmin) based on your roles mariadb and mysql_phpmyadmin.

Now I'm using 8.12.0 pgadmin image (only one tag associated with this image):
```
jupiter:~/git/toffee/smartserver # podman images | grep pga
mirror.gcr.io/dpage/pgadmin4                         8.12.0              a67d330eef3b  5 weeks ago    505 MB
``` 

but when the error appeared the pgadmin image had two tags associated - 8.11.0 and 8.11. I don't know how I ended here - maybe some leftovers in my systems. If you say that this should not happen because you cleanup upfront - then it's ok as it is. I will come back if this will happen again.
