### ISSUE TITLE
Make smartd alert temperature configurable

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#27]
From time to time in my system the SSD temperature goes over the 50 degree. I think it's normal (maximum operating temperature is 70 degree) because it drops after a while.

To avoid (false) alerts I prefer to have this temperature configurable. See my proposed [changes](https://github.com/toffee/smartserver/commit/4a8644312350003fbf346d63a5ee83b7d9bb5a56).

![image](https://github.com/user-attachments/assets/e87165cb-b375-423e-a46f-28452498b2c5)

**Comment by HolgerHees** [comment]
Looks good to me. It's also good that you found the syntax bug "> 50 > 50"

If you create a pull request, I will merge!

**Comment by toffee** [comment]
The PR is [here](https://github.com/HolgerHees/smartserver/pull/28).

**Comment by HolgerHees** [comment]
is merged https://github.com/HolgerHees/smartserver/commit/5583369a1a2ded74e708856d421d6162fc98a054
