### ISSUE TITLE
IndexError on roles/system_service/templates/opt/system_service_libs/lib/netflow/processor.py

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#9]
The query 
```
results = self.influxdb.query('SELECT "group","value" FROM "netflow_size" WHERE time >= now() - 358m AND "group"::tag != \'normal\'')
```
in my system returns an empty array. This leads to an exception (_IndexError: list index out of range_) [here](https://github.com/HolgerHees/smartserver/blob/6b04284674039c0a85c15d2b0776bd3ca51b6dc4/roles/system_service/templates/opt/system_service_libs/lib/netflow/processor.py#L801)

Adding a check if the array is empty solve the issue. Proposed changes in [this](https://github.com/toffee/smartserver/commit/3d3abb089417acc1a8f16e91a85349566ed4a587) commit.

Thank you!

**Comment by HolgerHees** [comment]
thanks for telling me. I refactored the related part a bit and it should be now more robust.

https://github.com/HolgerHees/smartserver/commit/4d9c97ccdab42cc27ce186ce4c7bcee50da58481#diff-089e2b2c8c5ef65780514639ac78a1417a04e2e4db10696f84606c377f846de4
